-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Form" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "formSubmissionCode" TEXT,
    "submissionDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" INTEGER,
    "completed" BOOLEAN NOT NULL DEFAULT false,
    "totalScore" INTEGER NOT NULL,
    "section1Score" INTEGER NOT NULL,
    "section2Score" INTEGER NOT NULL,
    "section3Score" INTEGER NOT NULL,
    "section4Score" INTEGER NOT NULL,
    "section5Score" INTEGER NOT NULL,
    "Q_1_1" TEXT NOT NULL,
    "Q_1_2" TEXT,
    "Q_1_3" TEXT,
    "Q_1_4" TEXT NOT NULL,
    "Q_1_5" TEXT NOT NULL,
    "Q_1_5_a" TEXT,
    "Q_1_6" TEXT,
    "Q_1_7" TEXT NOT NULL,
    "Q_2_1" TEXT NOT NULL,
    "Q_2_2" TEXT,
    "Q_2_2_a" TEXT,
    "Q_2_3" TEXT NOT NULL,
    "Q_2_3_a" TEXT,
    "Q_2_4" TEXT NOT NULL,
    "Q_2_4_a" TEXT,
    "Q_3_1" TEXT NOT NULL,
    "Q_3_1_a" TEXT,
    "Q_3_2" TEXT NOT NULL,
    "Q_3_2_a" TEXT,
    "Q_3_3" TEXT NOT NULL,
    "Q_3_3_a" TEXT,
    "Q_4_1" TEXT NOT NULL,
    "Q_4_1_a" TEXT NOT NULL,
    "Q_4_2" TEXT NOT NULL,
    "Q_4_2_a" TEXT,
    "Q_4_3" TEXT NOT NULL,
    "Q_4_4" TEXT NOT NULL,
    "Q_4_4_a" TEXT,
    "Q_4_5" TEXT NOT NULL,
    "Q_4_5_a" TEXT,
    "Q_4_6" TEXT NOT NULL,
    "Q_4_6_a" TEXT,
    "Q_4_7" TEXT NOT NULL,
    "Q_4_7_a" TEXT,
    "Q_4_8" TEXT NOT NULL,
    "Q_4_8_a" TEXT,
    "Q_4_9" TEXT NOT NULL,
    "Q_4_9_a" TEXT,
    "Q_4_10" TEXT NOT NULL,
    "Q_4_10_a" TEXT,
    "Q_5_1" TEXT NOT NULL,
    "Q_5_1_a" TEXT,
    "Q_5_2" TEXT NOT NULL,
    "Q_5_2_a" TEXT,
    "Q_5_3" TEXT NOT NULL,
    "Q_5_4" TEXT NOT NULL,
    "Q_5_4_a" TEXT,
    "Q_5_5" TEXT NOT NULL,
    "Q_5_5_a" TEXT,
    CONSTRAINT "Form_formSubmissionCode_fkey" FOREIGN KEY ("formSubmissionCode") REFERENCES "Delegate" ("formSubmissionCode") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Form_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Form" ("Q_1_1", "Q_1_2", "Q_1_3", "Q_1_4", "Q_1_5", "Q_1_5_a", "Q_1_6", "Q_1_7", "Q_2_1", "Q_2_2", "Q_2_2_a", "Q_2_3", "Q_2_3_a", "Q_2_4", "Q_2_4_a", "Q_3_1", "Q_3_1_a", "Q_3_2", "Q_3_2_a", "Q_3_3", "Q_3_3_a", "Q_4_1", "Q_4_10", "Q_4_10_a", "Q_4_1_a", "Q_4_2", "Q_4_2_a", "Q_4_3", "Q_4_4", "Q_4_4_a", "Q_4_5", "Q_4_5_a", "Q_4_6", "Q_4_6_a", "Q_4_7", "Q_4_7_a", "Q_4_8", "Q_4_8_a", "Q_4_9", "Q_4_9_a", "Q_5_1", "Q_5_1_a", "Q_5_2", "Q_5_2_a", "Q_5_3", "Q_5_4", "Q_5_4_a", "Q_5_5", "Q_5_5_a", "completed", "formSubmissionCode", "id", "section1Score", "section2Score", "section3Score", "section4Score", "section5Score", "totalScore", "userId") SELECT "Q_1_1", "Q_1_2", "Q_1_3", "Q_1_4", "Q_1_5", "Q_1_5_a", "Q_1_6", "Q_1_7", "Q_2_1", "Q_2_2", "Q_2_2_a", "Q_2_3", "Q_2_3_a", "Q_2_4", "Q_2_4_a", "Q_3_1", "Q_3_1_a", "Q_3_2", "Q_3_2_a", "Q_3_3", "Q_3_3_a", "Q_4_1", "Q_4_10", "Q_4_10_a", "Q_4_1_a", "Q_4_2", "Q_4_2_a", "Q_4_3", "Q_4_4", "Q_4_4_a", "Q_4_5", "Q_4_5_a", "Q_4_6", "Q_4_6_a", "Q_4_7", "Q_4_7_a", "Q_4_8", "Q_4_8_a", "Q_4_9", "Q_4_9_a", "Q_5_1", "Q_5_1_a", "Q_5_2", "Q_5_2_a", "Q_5_3", "Q_5_4", "Q_5_4_a", "Q_5_5", "Q_5_5_a", "completed", "formSubmissionCode", "id", "section1Score", "section2Score", "section3Score", "section4Score", "section5Score", "totalScore", "userId" FROM "Form";
DROP TABLE "Form";
ALTER TABLE "new_Form" RENAME TO "Form";
CREATE UNIQUE INDEX "Form_id_key" ON "Form"("id");
CREATE UNIQUE INDEX "Form_formSubmissionCode_key" ON "Form"("formSubmissionCode");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
